apiVersion: v1
kind: ConfigMap
metadata:
  name: respondnow-config
  namespace: respondnow
  labels:
    app.kubernetes.io/name: respondnow
data:
  SLACK_ENABLED: "false"
  MONGO_DATABASE: "respondnow"
  SERVER_PORT: "8080"
  JWT_EXPIRATION: "86400000"
  DEFAULT_USER_EMAIL: "admin@respondnow.io"
  DEFAULT_USER_NAME: "Admin"
  DEFAULT_ACCOUNT_ID: "default_account_id"
  DEFAULT_ACCOUNT_NAME: "Default Account"
  DEFAULT_ORG_ID: "default_org_id"
  DEFAULT_ORG_NAME: "Default Org"
  DEFAULT_PROJECT_ID: "default_project_id"
  DEFAULT_PROJECT_NAME: "Default Project"
