apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: respondnow-ingress
  namespace: respondnow
  labels:
    app.kubernetes.io/name: respondnow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: respondnow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: respondnow-portal
                port:
                  number: 8191
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: respondnow-server
                port:
                  number: 8080
