apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: respondnow

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - server.yaml
  - portal.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: respondnow
  app.kubernetes.io/managed-by: kustomize
